import Link from "next/link";
import { getDictionary } from "@sfrankey/i18n";
import { toolDefinitions, type Locale } from "@sfrankey/shared";
import { localePath } from "@/lib/locale";
import { Badge, Button, Card } from "@sfrankey/ui";

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const t = getDictionary(locale); return { title: locale === "vi" ? "Công cụ bảo mật và lập trình miễn phí" : "Free Security & Developer Tools", description: t.home.description }; }
export default async function HomePage({ params }: { params: Promise<{ locale: Locale }> }) { const { locale } = await params; const t = getDictionary(locale); const featured = toolDefinitions.filter((tool) => tool.featured); return <div><section className="relative overflow-hidden border-b border-slate-200 bg-gradient-to-br from-brand-50 via-white to-cyan-50 dark:border-slate-800 dark:from-brand-950/50 dark:via-slate-950 dark:to-cyan-950/30"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-center lg:py-28"><div><Badge>{t.home.eyebrow}</Badge><h1 className="mt-5 max-w-3xl text-4xl font-black tracking-tight text-slate-950 sm:text-6xl dark:text-white">{t.home.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">{t.home.description}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link href={localePath(locale, "tools")}>{t.home.cta} →</Link></Button><Button asChild variant="secondary"><Link href={localePath(locale, "privacy")}>{t.nav.privacy}</Link></Button></div></div><Card className="relative overflow-hidden bg-slate-950 text-white"><div className="absolute -right-16 -top-16 size-48 rounded-full bg-brand-500/30 blur-3xl" /><p className="relative text-sm font-semibold text-brand-200">{t.home.why}</p><p className="relative mt-3 text-2xl font-bold leading-tight">{t.home.whyText}</p><div className="relative mt-8 grid grid-cols-2 gap-3 text-xs text-slate-300"><div className="rounded-xl border border-white/10 bg-white/5 p-3">✓ {t.common.onDevice}</div><div className="rounded-xl border border-white/10 bg-white/5 p-3">✓ No account</div><div className="rounded-xl border border-white/10 bg-white/5 p-3">✓ Open source friendly</div><div className="rounded-xl border border-white/10 bg-white/5 p-3">✓ Việt / English</div></div></Card></div></section><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-600">{t.home.eyebrow}</p><h2 className="mt-2 text-3xl font-bold tracking-tight">{t.home.featured}</h2></div><Link className="text-sm font-semibold text-brand-600" href={localePath(locale, "tools")}>{t.nav.tools} →</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{featured.map((tool) => <ToolCard key={tool.id} locale={locale} tool={tool} />)}</div></section></div>; }
function ToolCard({ locale, tool }: { locale: Locale; tool: (typeof toolDefinitions)[number] }) { return <Link href={localePath(locale, `tools/${tool.slug}`)} className="group"><Card className="h-full transition hover:-translate-y-1 hover:border-brand-300 hover:shadow-lg dark:hover:border-brand-700"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-xl dark:bg-brand-950">{tool.icon}</span><span className="text-xs text-emerald-600">● On-device</span></div><h3 className="mt-5 font-bold group-hover:text-brand-600">{tool.title[locale]}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{tool.description[locale]}</p></Card></Link>; }
