"use client";
import * as React from "react";
import type { Locale } from "@sfrankey/shared";
import { getDictionary } from "@sfrankey/i18n";
import { Button, Input, Label, Textarea } from "@sfrankey/ui";

declare global { interface Window { turnstile?: { render: (element: HTMLElement, options: { sitekey: string; callback: (token: string) => void; "expired-callback": () => void; "error-callback": () => void }) => string; remove: (widgetId: string) => void } } }

export function FeedbackForm({ locale, kind }: { locale: Locale; kind: "bug_report" | "tool_request" }) {
  const t = getDictionary(locale); const [status, setStatus] = React.useState<"idle" | "loading" | "success" | "error">("idle"); const [form, setForm] = React.useState({ subject: "", message: "", email: "", website: "" }); const [turnstileToken, setTurnstileToken] = React.useState(""); const turnstileRef = React.useRef<HTMLDivElement>(null); const widgetId = React.useRef<string | null>(null); const siteKey = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
  React.useEffect(() => { if (!siteKey || !turnstileRef.current) return; const render = () => { if (window.turnstile && turnstileRef.current && !widgetId.current) widgetId.current = window.turnstile.render(turnstileRef.current, { sitekey: siteKey, callback: setTurnstileToken, "expired-callback": () => setTurnstileToken(""), "error-callback": () => setTurnstileToken("") }); }; if (window.turnstile) render(); else { const script = document.createElement("script"); script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"; script.async = true; script.defer = true; script.onload = render; document.head.appendChild(script); } return () => { if (widgetId.current && window.turnstile) window.turnstile.remove(widgetId.current); widgetId.current = null; }; }, [siteKey]);
  const update = (key: keyof typeof form, value: string) => setForm((old) => ({ ...old, [key]: value }));
  return <form className="max-w-xl space-y-4" onSubmit={async (event) => { event.preventDefault(); if (siteKey && !turnstileToken) { setStatus("error"); return; } setStatus("loading"); try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000"}/v1/feedback`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, kind, locale, pageUrl: window.location.href, turnstileToken }) }); if (!response.ok) throw new Error("Request failed"); setStatus("success"); setForm({ subject: "", message: "", email: "", website: "" }); setTurnstileToken(""); } catch { setStatus("error"); } }}><div><Label htmlFor="subject">{t.feedback.subject}</Label><Input id="subject" required minLength={3} maxLength={160} value={form.subject} onChange={(e) => update("subject", e.target.value)} /></div><div><Label htmlFor="message">{t.feedback.message}</Label><Textarea id="message" required minLength={10} maxLength={5000} value={form.message} onChange={(e) => update("message", e.target.value)} /></div><div><Label htmlFor="email">{t.feedback.email}</Label><Input id="email" type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></div><input aria-hidden="true" tabIndex={-1} autoComplete="off" className="absolute -left-[9999px]" value={form.website} onChange={(e) => update("website", e.target.value)} />{siteKey ? <div ref={turnstileRef} className="min-h-16" /> : null}<Button type="submit" disabled={status === "loading"}>{status === "loading" ? t.common.loading : t.feedback.submit}</Button>{status === "success" ? <p role="status" className="text-sm text-emerald-600">{t.feedback.success}</p> : null}{status === "error" ? <p role="alert" className="text-sm text-rose-600">{t.feedback.failure}</p> : null}</form>;
}
