"use client";
import * as React from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { getDictionary } from "@sfrankey/i18n";
import { toolDefinitions, type Locale } from "@sfrankey/shared";
import { Button, cn } from "@sfrankey/ui";
import { localePath } from "@/lib/locale";
import { readPreferences, writePreferences } from "@/lib/storage";
import { ThemeProvider, useTheme } from "./theme-provider";

export function Shell({ locale, children }: { locale: Locale; children: React.ReactNode }) { return <ThemeProvider><ShellInner locale={locale}>{children}</ShellInner></ThemeProvider>; }
function ShellInner({ locale, children }: { locale: Locale; children: React.ReactNode }) {
  const t = getDictionary(locale); const pathname = usePathname(); const router = useRouter(); const { theme, setTheme } = useTheme();
  const [query, setQuery] = React.useState(""); const [open, setOpen] = React.useState(false);
  const otherLocale = locale === "vi" ? "en" : "vi";
  const switchedPath = pathname.replace(/^\/(vi|en)/, `/${otherLocale}`);
  React.useEffect(() => { const prefs = readPreferences(); if (prefs.locale !== locale) writePreferences({ ...prefs, locale }); document.cookie = `sfrankey-locale=${locale};path=/;max-age=31536000;samesite=lax`; }, [locale]);
  React.useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen(true); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  return <div className="min-h-screen"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-4 sm:px-6"><Link href={localePath(locale)} className="flex min-w-0 items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-brand-500 font-black text-white">S</span><span className="hidden sm:block"><span className="block text-sm font-black tracking-tight">SFranKey</span><span className="block text-[10px] font-medium text-slate-500">{t.brandDescriptor}</span></span></Link><button type="button" onClick={() => setOpen(true)} className="ml-auto flex h-10 min-w-0 flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3 text-left text-sm text-slate-400 hover:bg-slate-50 sm:ml-8 sm:max-w-sm dark:border-slate-800 dark:hover:bg-slate-900"><span>⌕</span><span className="truncate">{t.common.search}</span><kbd className="ml-auto hidden rounded border px-1.5 py-0.5 text-[10px] sm:block">Ctrl K</kbd></button><nav className="hidden items-center gap-1 lg:flex"><Link className="rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-900" href={localePath(locale, "tools")}>{t.nav.tools}</Link><Link className="rounded-lg px-3 py-2 text-sm text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-900" href={localePath(locale, "about")}>{t.nav.about}</Link></nav><select aria-label="Theme" value={theme} onChange={(e) => setTheme(e.target.value as "light" | "dark" | "system")} className="hidden h-9 rounded-lg border border-slate-200 bg-transparent px-2 text-xs sm:block dark:border-slate-800"><option value="system">◐</option><option value="light">☼</option><option value="dark">☾</option></select><Link href={switchedPath} className="rounded-lg border border-slate-200 px-2.5 py-2 text-xs font-semibold dark:border-slate-800">{otherLocale.toUpperCase()}</Link></div></header><main>{children}</main><footer className="border-t border-slate-200 dark:border-slate-800"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="font-bold text-slate-800 dark:text-slate-200">SFranKey</p><p>{t.tagline}</p></div><div className="flex flex-wrap gap-4"><Link href={localePath(locale, "privacy")}>{t.nav.privacy}</Link><Link href={localePath(locale, "security")}>{t.nav.security}</Link><Link href={localePath(locale, "request-a-tool")}>{t.nav.request}</Link></div></div></footer>{open ? <SearchDialog locale={locale} query={query} setQuery={setQuery} close={() => { setOpen(false); setQuery(""); }} onSelect={(slug) => { setOpen(false); router.push(localePath(locale, `tools/${slug}`)); }} /> : null}</div>;
}
function SearchDialog({ locale, query, setQuery, close, onSelect }: { locale: Locale; query: string; setQuery: (value: string) => void; close: () => void; onSelect: (slug: string) => void }) { const t = getDictionary(locale); const results = toolDefinitions.filter((tool) => `${tool.title[locale]} ${tool.description[locale]} ${tool.keywords.join(" ")}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8); return <div className="fixed inset-0 z-50 grid place-items-start bg-slate-950/50 p-4 pt-[12vh]" onMouseDown={close}><div role="dialog" aria-modal="true" className="mx-auto w-full max-w-xl rounded-2xl border border-slate-200 bg-white p-3 shadow-2xl dark:border-slate-700 dark:bg-slate-900" onMouseDown={(e) => e.stopPropagation()}><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t.common.search} className="h-12 w-full rounded-xl bg-slate-100 px-4 outline-none dark:bg-slate-950" /> <div className="mt-2 max-h-[55vh] overflow-y-auto">{results.map((tool) => <button type="button" key={tool.id} onClick={() => onSelect(tool.slug)} className="flex w-full items-start gap-3 rounded-xl p-3 text-left hover:bg-slate-100 dark:hover:bg-slate-800"><span className="grid size-9 place-items-center rounded-lg bg-brand-50 dark:bg-brand-950">{tool.icon}</span><span><strong className="block text-sm">{tool.title[locale]}</strong><span className="text-xs text-slate-500">{tool.description[locale]}</span></span></button>)}{!results.length ? <p className="p-4 text-sm text-slate-500">{t.common.noResults}</p> : null}</div></div></div>; }
