"use client";
import * as React from "react";
import { getDictionary } from "@sfrankey/i18n";
import type { Locale } from "@sfrankey/shared";
import { Button, Card, CopyButton, Input, Label, Select, Textarea } from "@sfrankey/ui";
import { assessPassword, compareHashes, createQrDataUrl, createQrSvg, decodeBase64, decodeJwt, encodeBase64, generateOtp, generatePassword, generateUuids, hashFile, hashText, otpRemainingSeconds, parseOtpAuth, formatJson, minifyJson, relativeTime, timestampToDate, dateToTimestamp, scanQrImage, type HashAlgorithm } from "@sfrankey/tool-core";
import { trackToolUsed } from "@/lib/analytics";
import { recordRecentTool } from "@/lib/storage";
import { TwoFactorWorkspace } from "@/components/two-factor-workspace";

export function ToolClient({ locale, slug }: { locale: Locale; slug: string }) {
  React.useEffect(() => { trackToolUsed(slug); recordRecentTool(slug); }, [slug]);
  switch (slug) {
    case "totp-generator": return <TwoFactorWorkspace locale={locale} initialTab="secret" />;
    case "qr-2fa-scanner": return <TwoFactorWorkspace locale={locale} initialTab="scan" />;
    case "password-generator": return <PasswordGeneratorTool locale={locale} />;
    case "password-strength-checker": return <PasswordCheckerTool locale={locale} />;
    case "qr-generator": return <QrGeneratorTool locale={locale} />;
    case "qr-reader": return <QrScannerTool locale={locale} mode="general" />;
    case "base64-encode-decode": return <Base64Tool locale={locale} />;
    case "hash-generator": return <HashTool locale={locale} />;
    case "file-checksum": return <ChecksumTool locale={locale} />;
    case "jwt-decoder": return <JwtTool locale={locale} />;
    case "json-formatter": return <JsonTool locale={locale} />;
    case "uuid-generator": return <UuidTool locale={locale} />;
    case "timestamp-converter": return <TimestampTool locale={locale} />;
    default: return null;
  }
}

function Workspace({ children }: { children: React.ReactNode }) { return <Card className="max-w-4xl">{children}</Card>; }
function ToolHeading({ children }: { children: React.ReactNode }) { return <h2 className="mb-5 text-lg font-bold">{children}</h2>; }
function ErrorText({ message }: { message: string }) { return message ? <p role="alert" className="mt-3 text-sm text-rose-600">{message}</p> : null; }
function Row({ children }: { children: React.ReactNode }) { return <div className="flex flex-wrap items-center gap-3">{children}</div>; }

function TotpTool({ locale }: { locale: Locale }) {
  const t = getDictionary(locale); const [secret, setSecret] = React.useState(""); const [uri, setUri] = React.useState(""); const [algorithm, setAlgorithm] = React.useState<"SHA-1" | "SHA-256" | "SHA-512">("SHA-1"); const [digits, setDigits] = React.useState<6 | 8>(6); const [period, setPeriod] = React.useState(30); const [otp, setOtp] = React.useState(""); const [error, setError] = React.useState(""); const [remaining, setRemaining] = React.useState(30);
  React.useEffect(() => { const tick = async () => { try { const value = uri ? parseOtpAuth(uri) : null; const nextSecret = value?.secret ?? secret; if (!nextSecret) { setOtp(""); setRemaining(otpRemainingSeconds(Date.now(), value?.period ?? period)); return; } setOtp(await generateOtp({ secret: nextSecret, algorithm: value?.algorithm ?? algorithm, digits: value?.digits ?? digits, period: value?.period ?? period })); setRemaining(otpRemainingSeconds(Date.now(), value?.period ?? period)); setError(""); } catch (e) { setOtp(""); setError(e instanceof Error ? e.message : t.common.invalid); } }; void tick(); const timer = window.setInterval(() => void tick(), 1000); return () => window.clearInterval(timer); }, [secret, uri, algorithm, digits, period, t.common.invalid]);
  return <Workspace><ToolHeading>{locale === "vi" ? "Nhập secret hoặc otpauth URI" : "Enter a secret or otpauth URI"}</ToolHeading><div className="grid gap-4"><div><Label htmlFor="totp-secret">Secret (Base32)</Label><Input id="totp-secret" type="password" value={secret} onChange={(e) => { setSecret(e.target.value); setUri(""); }} placeholder="JBSWY3DPEHPK3PXP" autoComplete="off" /></div><div><Label htmlFor="totp-uri">otpauth:// URI</Label><Textarea id="totp-uri" value={uri} onChange={(e) => { setUri(e.target.value); setSecret(""); }} placeholder="otpauth://totp/Example:account?..." autoComplete="off" /></div><div className="grid gap-4 sm:grid-cols-3"><div><Label>Algorithm</Label><Select value={algorithm} onChange={(e) => setAlgorithm(e.target.value as typeof algorithm)}><option>SHA-1</option><option>SHA-256</option><option>SHA-512</option></Select></div><div><Label>Digits</Label><Select value={digits} onChange={(e) => setDigits(Number(e.target.value) as 6 | 8)}><option value="6">6</option><option value="8">8</option></Select></div><div><Label>Period</Label><Select value={period} onChange={(e) => setPeriod(Number(e.target.value))}><option value="30">30 seconds</option><option value="60">60 seconds</option></Select></div></div></div><ErrorText message={error} />{otp ? <div className="mt-6 rounded-2xl bg-slate-950 p-6 text-center text-white"><p className="text-xs uppercase tracking-[0.25em] text-slate-400">Current OTP</p><p className="mt-2 font-mono text-5xl font-bold tracking-[0.2em]">{otp}</p><div className="mx-auto mt-5 h-2 max-w-xs overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-brand-400 transition-all" style={{ width: `${(remaining / period) * 100}%` }} /></div><p className="mt-2 text-sm text-slate-400">{remaining}s</p><div className="mt-4"><CopyButton value={otp} label={t.common.copy} /></div></div> : null}<p className="mt-5 text-xs text-slate-500">{locale === "vi" ? "Secret chỉ được xử lý trong trình duyệt, không đưa vào URL hoặc gửi lên server." : "The secret is processed in this browser and is never added to the URL or sent to the server."}</p></Workspace>;
}

function QrScannerTool({ locale, mode }: { locale: Locale; mode: "2fa" | "general" }) {
  const [result, setResult] = React.useState(""); const [error, setError] = React.useState(""); const [camera, setCamera] = React.useState(false); const videoRef = React.useRef<HTMLVideoElement>(null); const streamRef = React.useRef<MediaStream | null>(null); const canvasRef = React.useRef<HTMLCanvasElement>(null);
  const scanFile = React.useCallback(async (file: File) => { if (file.size > 10 * 1024 * 1024) { setError("Image must be smaller than 10 MB."); return; } try { const bitmap = await createImageBitmap(file); const canvas = canvasRef.current ?? document.createElement("canvas"); canvas.width = bitmap.width; canvas.height = bitmap.height; const context = canvas.getContext("2d"); if (!context) throw new Error("Canvas is unavailable"); context.drawImage(bitmap, 0, 0); const value = scanQrImage(context.getImageData(0, 0, canvas.width, canvas.height)); if (!value) throw new Error("No QR code was found in this image"); setResult(value); setError(""); bitmap.close(); } catch (e) { setError(e instanceof Error ? e.message : "Could not read the image"); } }, []);
  const stopCamera = React.useCallback(() => { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; setCamera(false); }, []);
  React.useEffect(() => () => stopCamera(), [stopCamera]);
  React.useEffect(() => { const handlePaste = (event: ClipboardEvent) => { const file = event.clipboardData?.files?.[0]; if (file?.type.startsWith("image/")) void scanFile(file); }; window.addEventListener("paste", handlePaste); return () => window.removeEventListener("paste", handlePaste); }, [scanFile]);
  React.useEffect(() => { if (!camera) return; let cancelled = false; void (async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); if (cancelled) { stream.getTracks().forEach((track) => track.stop()); return; } streamRef.current = stream; if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } const loop = () => { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas || video.readyState < 2 || cancelled) { if (!cancelled) requestAnimationFrame(loop); return; } canvas.width = video.videoWidth; canvas.height = video.videoHeight; const context = canvas.getContext("2d"); if (!context) return; context.drawImage(video, 0, 0, canvas.width, canvas.height); const value = scanQrImage(context.getImageData(0, 0, canvas.width, canvas.height)); if (value) { setResult(value); stopCamera(); } else requestAnimationFrame(loop); }; requestAnimationFrame(loop); } catch { setError("Camera permission was not available."); setCamera(false); } })(); return () => { cancelled = true; }; }, [camera, stopCamera]);
  return <Workspace><ToolHeading>{mode === "2fa" ? (locale === "vi" ? "Đọc QR 2FA" : "Read a 2FA QR") : (locale === "vi" ? "Đọc QR cục bộ" : "Read a QR locally")}</ToolHeading><div className="flex flex-wrap gap-3"><label className="inline-flex min-h-10 cursor-pointer items-center rounded-xl bg-brand-500 px-4 py-2 text-sm font-semibold text-white hover:bg-brand-600"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => { const file = e.target.files?.[0]; if (file) void scanFile(file); e.currentTarget.value = ""; }} />Upload image</label><Button type="button" variant="secondary" onClick={() => setCamera((value) => !value)}>{camera ? "Stop camera" : "Use camera"}</Button></div>{camera ? <video ref={videoRef} className="mt-5 aspect-video w-full rounded-xl bg-slate-950 object-cover" muted playsInline /> : null}<canvas ref={canvasRef} className="hidden" /><ErrorText message={error} />{result ? <div className="mt-5 grid gap-3"><Label>Decoded content</Label><Textarea value={result} readOnly /><Row><CopyButton value={result} /><Button type="button" variant="secondary" onClick={() => { if (/^https?:\/\//i.test(result) && window.confirm(locale === "vi" ? "Chỉ mở liên kết này nếu bạn tin tưởng nội dung QR." : "Only open this link if you trust the QR content.")) window.open(result, "_blank", "noopener,noreferrer"); }}>{locale === "vi" ? "Mở liên kết" : "Open link"}</Button></Row>{mode === "2fa" && result.startsWith("otpauth://") ? <p className="text-sm text-emerald-600">otpauth:// detected — paste this into TOTP Generator. Secret remains local.</p> : null}</div> : null}<p className="mt-5 text-xs text-slate-500">{locale === "vi" ? "Ảnh và camera được xử lý trên thiết bị. Kiểm tra nội dung trước khi mở liên kết." : "Images and camera frames are processed on this device. Check content before opening links."}</p></Workspace>;
}

function PasswordGeneratorTool({ locale }: { locale: Locale }) { const t = getDictionary(locale); const [length, setLength] = React.useState(20); const [options, setOptions] = React.useState({ uppercase: true, lowercase: true, numbers: true, symbols: true, excludeAmbiguous: false, noRepeat: false }); const [values, setValues] = React.useState<string[]>([]); const [error, setError] = React.useState(""); const toggle = (key: keyof typeof options) => setOptions((old) => ({ ...old, [key]: !old[key] })); return <Workspace><ToolHeading>{locale === "vi" ? "Tạo mật khẩu bằng CSPRNG" : "Generate passwords with CSPRNG"}</ToolHeading><div className="grid gap-4 sm:grid-cols-2"><div><Label>Length: {length}</Label><input aria-label="Password length" type="range" min="4" max="128" value={length} onChange={(e) => setLength(Number(e.target.value))} className="w-full accent-brand-500" /></div><div className="grid grid-cols-2 gap-2 text-sm">{Object.entries({ uppercase: "Uppercase", lowercase: "Lowercase", numbers: "Numbers", symbols: "Symbols", excludeAmbiguous: "Exclude ambiguous", noRepeat: "No repeated characters" }).map(([key, label]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={options[key as keyof typeof options]} onChange={() => toggle(key as keyof typeof options)} />{label}</label>)}</div></div><Row><Button type="button" onClick={() => { try { setValues(Array.from({ length: 3 }, () => generatePassword({ length, ...options }))); setError(""); } catch (e) { setError(e instanceof Error ? e.message : t.common.invalid); } }}>{t.common.generate}</Button>{values.length ? <Button type="button" variant="secondary" onClick={() => void navigator.clipboard.writeText(values.join("\n"))}>{t.common.copy} all</Button> : null}</Row><ErrorText message={error} />{values.length ? <div className="mt-5 space-y-2">{values.map((value) => <div key={value} className="flex items-center gap-2 rounded-xl bg-slate-100 p-3 dark:bg-slate-950"><code className="min-w-0 flex-1 break-all text-sm">{value}</code><CopyButton value={value} /></div>)}</div> : null}</Workspace>; }

function PasswordCheckerTool({ locale }: { locale: Locale }) { const [value, setValue] = React.useState(""); const result = assessPassword(value); const labels = locale === "vi" ? { "very-weak": "Rất yếu", weak: "Yếu", medium: "Trung bình", strong: "Mạnh", "very-strong": "Rất mạnh" } : { "very-weak": "Very weak", weak: "Weak", medium: "Medium", strong: "Strong", "very-strong": "Very strong" }; return <Workspace><ToolHeading>{locale === "vi" ? "Kiểm tra cục bộ" : "Check locally"}</ToolHeading><Label htmlFor="password-check">Password</Label><Input id="password-check" type="password" value={value} onChange={(e) => setValue(e.target.value)} autoComplete="off" /><div className="mt-5 rounded-xl bg-slate-100 p-4 dark:bg-slate-950"><div className="flex items-center justify-between"><strong>{labels[result.label]}</strong><span className="text-sm text-slate-500">{result.entropy} bits est.</span></div><div className="mt-3 grid grid-cols-5 gap-1">{[0, 1, 2, 3, 4].map((score) => <span key={score} className={`h-2 rounded-full ${score <= result.score ? result.score < 2 ? "bg-rose-500" : result.score < 4 ? "bg-amber-500" : "bg-emerald-500" : "bg-slate-200 dark:bg-slate-800"}`} />)}</div></div>{result.suggestions.length ? <ul className="mt-4 list-disc pl-5 text-sm text-slate-500">{result.suggestions.map((suggestion) => <li key={suggestion}>{suggestion}</li>)}</ul> : null}<p className="mt-5 text-xs text-slate-500">{locale === "vi" ? "Mật khẩu không được lưu hoặc gửi đi." : "The password is not stored or sent anywhere."}</p></Workspace>; }

function QrGeneratorTool({ locale }: { locale: Locale }) { const [value, setValue] = React.useState("https://sfrankey.com"); const [dataUrl, setDataUrl] = React.useState(""); const [error, setError] = React.useState(""); React.useEffect(() => { void createQrDataUrl(value).then(setDataUrl).catch((e) => setError(e instanceof Error ? e.message : "Invalid content")); }, [value]); return <Workspace><ToolHeading>{locale === "vi" ? "Tạo QR từ nội dung" : "Create a QR from content"}</ToolHeading><Label htmlFor="qr-value">Text or URL</Label><Textarea id="qr-value" value={value} onChange={(e) => setValue(e.target.value)} /><ErrorText message={error} />{dataUrl ? <div className="mt-5 flex flex-col items-center gap-4"><img src={dataUrl} alt="Generated QR code" className="size-64 rounded-xl border bg-white p-3" /><Row><Button type="button" onClick={() => { const link = document.createElement("a"); link.href = dataUrl; link.download = "sfrankey-qr.png"; link.click(); }}>{locale === "vi" ? "Tải PNG" : "Download PNG"}</Button><Button type="button" variant="secondary" onClick={async () => { const svg = await createQrSvg(value); const blob = new Blob([svg], { type: "image/svg+xml" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "sfrankey-qr.svg"; link.click(); URL.revokeObjectURL(link.href); }}>{locale === "vi" ? "Tải SVG" : "Download SVG"}</Button></Row></div> : null}</Workspace>; }

function Base64Tool({ locale }: { locale: Locale }) { const [input, setInput] = React.useState(""); const [mode, setMode] = React.useState<"encode" | "decode">("encode"); const [urlSafe, setUrlSafe] = React.useState(false); const [output, setOutput] = React.useState(""); const [error, setError] = React.useState(""); const t = getDictionary(locale); const run = () => { try { setOutput(mode === "encode" ? encodeBase64(input, urlSafe) : decodeBase64(input, urlSafe)); setError(""); } catch (e) { setOutput(""); setError(e instanceof Error ? e.message : t.common.invalid); } }; return <Workspace><ToolHeading>Base64 Encode / Decode</ToolHeading><div className="flex flex-wrap gap-3"><Select value={mode} onChange={(e) => setMode(e.target.value as typeof mode)}><option value="encode">Encode</option><option value="decode">Decode</option></Select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={urlSafe} onChange={(e) => setUrlSafe(e.target.checked)} />URL-safe</label></div><Label className="mt-4" htmlFor="base64-input">Input</Label><Textarea id="base64-input" value={input} onChange={(e) => setInput(e.target.value)} /><Row><Button type="button" onClick={run}>{mode === "encode" ? "Encode" : "Decode"}</Button>{output ? <CopyButton value={output} /> : null}</Row><ErrorText message={error} />{output ? <pre className="mt-5 max-h-72 overflow-auto whitespace-pre-wrap break-all rounded-xl bg-slate-100 p-4 text-sm dark:bg-slate-950">{output}</pre> : null}<p className="mt-5 text-xs text-slate-500">{t.tool.noEncryption}</p></Workspace>; }

function HashTool({ locale }: { locale: Locale }) { const [input, setInput] = React.useState(""); const [algorithm, setAlgorithm] = React.useState<HashAlgorithm>("SHA-256"); const [format, setFormat] = React.useState<"hex" | "base64">("hex"); const [output, setOutput] = React.useState(""); const [compare, setCompare] = React.useState(""); const [error, setError] = React.useState(""); return <Workspace><ToolHeading>{locale === "vi" ? "Tạo hash từ văn bản" : "Hash text locally"}</ToolHeading><Textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="Text to hash" /><Row><Select value={algorithm} onChange={(e) => setAlgorithm(e.target.value as HashAlgorithm)}><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></Select><Select value={format} onChange={(e) => setFormat(e.target.value as typeof format)}><option value="hex">Hex</option><option value="base64">Base64</option></Select><Button type="button" onClick={async () => { try { setOutput(await hashText(input, algorithm, format)); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not hash"); } }}>Hash</Button></Row><ErrorText message={error} />{output ? <div className="mt-5 space-y-3"><div className="flex items-start gap-2 rounded-xl bg-slate-100 p-3 dark:bg-slate-950"><code className="min-w-0 flex-1 break-all text-sm">{output}</code><CopyButton value={output} /></div><Input value={compare} onChange={(e) => setCompare(e.target.value)} placeholder="Paste expected hash to compare" />{compare ? <p className={compareHashes(output, compare) ? "text-sm text-emerald-600" : "text-sm text-rose-600"}>{compareHashes(output, compare) ? "✓ Match" : "✕ Does not match"}</p> : null}</div> : null}</Workspace>; }

function ChecksumTool({ locale }: { locale: Locale }) { const [file, setFile] = React.useState<File | null>(null); const [expected, setExpected] = React.useState(""); const [algorithm, setAlgorithm] = React.useState<HashAlgorithm>("SHA-256"); const [result, setResult] = React.useState(""); const [error, setError] = React.useState(""); return <Workspace><ToolHeading>{locale === "vi" ? "Tính checksum file" : "Hash a local file"}</ToolHeading><input type="file" onChange={(e) => { const selected = e.target.files?.[0] ?? null; if (selected && selected.size > 200 * 1024 * 1024) { setError("File must be smaller than 200 MB."); setFile(null); } else { setFile(selected); setError(""); } }} /><Row><Select value={algorithm} onChange={(e) => setAlgorithm(e.target.value as HashAlgorithm)}><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></Select><Button type="button" disabled={!file} onClick={async () => { if (!file) return; try { setResult(await hashFile(file, algorithm)); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not hash file"); } }}>Checksum</Button></Row><Input value={expected} onChange={(e) => setExpected(e.target.value)} placeholder="Expected checksum (optional)" /><ErrorText message={error} />{result ? <div className="mt-4"><code className="block break-all rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-950">{result}</code><div className="mt-3 flex items-center gap-3"><CopyButton value={result} />{expected ? <span className={compareHashes(result, expected) ? "text-sm text-emerald-600" : "text-sm text-rose-600"}>{compareHashes(result, expected) ? "✓ Match" : "✕ Does not match"}</span> : null}</div></div> : null}</Workspace>; }

function JwtTool({ locale }: { locale: Locale }) { const t = getDictionary(locale); const [input, setInput] = React.useState(""); const [decoded, setDecoded] = React.useState<ReturnType<typeof decodeJwt> | null>(null); const [error, setError] = React.useState(""); return <Workspace><ToolHeading>JWT Decoder</ToolHeading><Textarea value={input} onChange={(e) => setInput(e.target.value)} placeholder="eyJhbGciOi..." autoComplete="off" /><Row><Button type="button" onClick={() => { try { setDecoded(decodeJwt(input)); setError(""); } catch (e) { setDecoded(null); setError(e instanceof Error ? e.message : t.common.invalid); } }}>Decode</Button>{decoded ? <CopyButton value={JSON.stringify(decoded.payload, null, 2)} /> : null}</Row><ErrorText message={error} />{decoded ? <div className="mt-5 grid gap-4 md:grid-cols-3">{[["Header", decoded.header], ["Payload", decoded.payload], ["Signature", decoded.signature]].map(([name, value]) => <div key={String(name)}><Label>{String(name)}</Label><pre className="max-h-72 overflow-auto whitespace-pre-wrap break-all rounded-xl bg-slate-100 p-3 text-xs dark:bg-slate-950">{typeof value === "string" ? value : JSON.stringify(value, null, 2)}</pre></div>)}</div> : null}<p className="mt-5 text-xs text-amber-600">{t.tool.noVerification}</p></Workspace>; }

function JsonTool({ locale }: { locale: Locale }) { const t = getDictionary(locale); const [input, setInput] = React.useState("{\n  \"hello\": \"world\"\n}"); const [output, setOutput] = React.useState(""); const [error, setError] = React.useState(""); const [sortKeys, setSortKeys] = React.useState(false); const run = (compact = false) => { if (input.length > 5 * 1024 * 1024) { setError("JSON must be smaller than 5 MB."); return; } try { setOutput(compact ? minifyJson(input, sortKeys) : formatJson(input, 2, sortKeys)); setError(""); } catch (e) { setOutput(""); setError(e instanceof Error ? e.message : t.common.invalid); } }; return <Workspace><ToolHeading>JSON Formatter</ToolHeading><Textarea className="min-h-64 font-mono" value={input} onChange={(e) => setInput(e.target.value)} /><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={sortKeys} onChange={(e) => setSortKeys(e.target.checked)} />Sort keys</label><Row><Button type="button" onClick={() => run(false)}>Format</Button><Button type="button" variant="secondary" onClick={() => run(true)}>Minify</Button>{output ? <CopyButton value={output} /> : null}</Row><ErrorText message={error} />{output ? <pre className="mt-5 max-h-96 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-100 p-4 font-mono text-sm dark:bg-slate-950">{output}</pre> : null}</Workspace>; }

function UuidTool({ locale }: { locale: Locale }) { const [count, setCount] = React.useState(5); const [values, setValues] = React.useState<string[]>([]); return <Workspace><ToolHeading>{locale === "vi" ? "Tạo UUID v4" : "Generate UUID v4"}</ToolHeading><Row><Input className="w-28" type="number" min="1" max="1000" value={count} onChange={(e) => setCount(Number(e.target.value))} /><Button type="button" onClick={() => setValues(generateUuids(count))}>{getDictionary(locale).common.generate}</Button>{values.length ? <CopyButton value={values.join("\n")} /> : null}</Row>{values.length ? <pre className="mt-5 max-h-80 overflow-auto rounded-xl bg-slate-100 p-4 font-mono text-sm dark:bg-slate-950">{values.join("\n")}</pre> : null}</Workspace>; }

function TimestampTool({ locale }: { locale: Locale }) { const [input, setInput] = React.useState(String(Math.floor(Date.now() / 1000))); const [unit, setUnit] = React.useState<"seconds" | "milliseconds">("seconds"); const [output, setOutput] = React.useState(""); const [error, setError] = React.useState(""); const [dateInput, setDateInput] = React.useState(new Date().toISOString().slice(0, 16)); const convert = () => { try { const date = timestampToDate(Number(input), unit); setOutput(`${date.toISOString()}\nLocal: ${date.toLocaleString()}\nRelative: ${relativeTime(date)}`); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Invalid timestamp"); } }; const reverse = () => { const date = new Date(dateInput); if (Number.isNaN(date.getTime())) { setError("Invalid date"); return; } setInput(String(dateToTimestamp(date, unit))); setError(""); }; return <Workspace><ToolHeading>Unix Timestamp Converter</ToolHeading><div className="grid gap-4 sm:grid-cols-2"><div><Label>Timestamp</Label><Input value={input} onChange={(e) => setInput(e.target.value)} /><Select className="mt-2" value={unit} onChange={(e) => setUnit(e.target.value as typeof unit)}><option value="seconds">Seconds</option><option value="milliseconds">Milliseconds</option></Select></div><div><Label>ISO/local date</Label><Input type="datetime-local" value={dateInput} onChange={(e) => setDateInput(e.target.value)} /><Button className="mt-2" type="button" variant="secondary" onClick={reverse}>Date → timestamp</Button></div></div><Row><Button type="button" onClick={convert}>Timestamp → date</Button>{output ? <CopyButton value={output} /> : null}</Row><ErrorText message={error} />{output ? <pre className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-100 p-4 text-sm dark:bg-slate-950">{output}</pre> : null}</Workspace>; }
